# Generated by Django 3.2.5 on 2021-10-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='disease',
        ),
    ]
